apiVersion: v1
kind: Service
metadata:
  name: your-app-your-environment
  namespace: your-app-your-environment
  labels:
    app: your-app-your-environment
spec:
  ports:
  - port: 3030
    targetPort: http
    protocol: TCP
    name: http
  selector:
    app: your-app-your-environment
    # tier: frontend
